### ISSUE TITLE
[Important] Need to reintroduce traffic analytics

### ISSUE THREAD

**Issue by ribasushi** [dbsrgits/dbic-web#12]
@castaway If you can look into getting the code from the old site while we are driving it'd be grand!

**Comment by castaway** [comment]
Will do

**Comment by ribasushi** [comment]
@castaway @shadowcat-mdk @idnorton Did we ever get anywhere with this?

**Comment by shadowcat-mdk** [comment]
Might have helped had I seen it :( Castaway did you pull a copy down from Google Analytics?

**Comment by shadowcat-mdk** [comment]
Paste this into every page we wish to track: 

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-17806002-1', 'auto');
  ga('send', 'pageview');
</script>

**Comment by shadowcat-mdk** [comment]
ribasushi: What is a google email for you so that I can add you to the Analytics account - that way you will be able to view, edit, manage and play with the stats.

**Comment by ribasushi** [comment]
@shadowcat-mdk ribasushi@...

**Comment by castaway** [comment]
iirc was done ages ago..

**Comment by ribasushi** [comment]
@castaway - I did not know it was, and had no access, so assumed "If open - then not done" :)
Closing then
